### ISSUE TITLE
Empty Button Actions

### ISSUE THREAD

**Issue by Phorzaeken** [vis2k/uMMORPG#34] opened 2020-03-06 20:00 UTC
**Versions (please complete the following information)**
 - Unity Version: 2019.2.14f1
 - uMMORPG Version: V1.187
 - Are you using a fresh uMMORPG version without any modifications? [Yes]
    If not, then please try to reproduce it in a fresh Version and come back here.

**Describe the bug**
The game buttons: 
On a player click in-game, Trade and Add Party don't do anything. There is no invite to guild button also.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open built game application twice.
2. Login and Server & Play twice.
3. Go to other player and click them.
4. Trade button and Add Party button appear.
5. Clicking the buttons don't have any action.

**Expected behavior**

A trade menu should appear but it did not. Same for the add party button.

**Screenshots/Video**
If applicable, add screenshots/videos to help explain your problem.

**System (please complete the following information):**
 - Operating System: Windows 10

**Additional context**
Is there something missing? Also, is there a trade window? In the Discord Server, I found messages about this issue in 'uMMORPG CE' but I'm using uMMORPG 3D Classic.

**Comment by miwarnec** [comment] 2020-03-07 16:27
@Phorsion you need to stand close to the other player for those to work.
if you are too far away it doesn't work (as intended)

**Comment by Phorzaeken** [comment] 2020-03-07 16:36
What file or component do I go into to change the range? I was a short finger distance away and would like a little more distance for trading and such. Also, where is the add to guild button? Sent from Mail for Windows 10 From: vis2kSent: Saturday, March 7, 2020 8:27 AMTo: vis2k/uMMORPGCc: Phorsion; MentionSubject: Re: [vis2k/uMMORPG] Empty Button Actions (#34) @Phorsion you need to stand close to the other player for those to work.if you are too far away it doesn't work (as intended)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Phorzaeken** [comment] 2020-03-07 16:48
Actually the distance is fine. But the trade and party invite buttons don’t work when lit up. I changed my class to both warrior by the way. Sent from Mail for Windows 10 From: vis2kSent: Saturday, March 7, 2020 8:27 AMTo: vis2k/uMMORPGCc: Phorsion; MentionSubject: Re: [vis2k/uMMORPG] Empty Button Actions (#34) @Phorsion you need to stand close to the other player for those to work.if you are too far away it doesn't work (as intended)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Phorzaeken** [comment] 2020-03-07 17:08
Using the search bar on the project tab, I search for trading and see the prefab and scripts for trading. I think I have to set up drag and droppables onto the prefab, the script(s) or both. What do I modify by dragging and dropping in? Here is the SlotPlayerTrading Prefab: Here is the UIPlayerTrading Import Settings Script: Here is the UIPlayerTradingSlot Import Settings Script: Sent from Mail for Windows 10 From: vis2kSent: Saturday, March 7, 2020 8:27 AMTo: vis2k/uMMORPGCc: Phorsion; MentionSubject: Re: [vis2k/uMMORPG] Empty Button Actions (#34) @Phorsion you need to stand close to the other player for those to work.if you are too far away it doesn't work (as intended)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iamallama** [comment] 2020-03-08 01:24
@Phorsion The guild button doesn't show unless you are in a guild and a sufficient enough level to invite someone. Have you created a guild to test the guild button yet?

**Comment by Phorzaeken** [comment] 2020-03-08 04:23
I haven’t created a guild yet, and did not look into the scripts or components to see if the inputs are empty like trade and party invite. Sent from Mail for Windows 10 From: iamallamaSent: Saturday, March 7, 2020 5:24 PMTo: vis2k/uMMORPGCc: Phorsion; MentionSubject: Re: [vis2k/uMMORPG] Empty Button Actions (#34) @Phorsion The guild button doesn't show unless you are in a guild and a sufficient enough level to invite someone. Have you created a guild to test the guild button yet?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by miwarnec** [comment] 2020-03-12 20:40
doesn't seem to be a bug, rather user error.
@Phorsion please take your time and play around ummorpg a bit :)
closing this for now. it's hard to read with the strange formatting too.

**Closed as completed by miwarnec** 2020-03-12 20:40 UTC
