### ISSUE TITLE
Guild Member status is not updated

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#25] opened 2019-11-11 17:18 UTC
Blank uMMORPG3d (or 2d, does not matter in that case) of most recent version

The status of guild members is broadcasted only on CharacterLoad, then never more.

Shouldn't it be updated both in Start and OnDestroy?

**Comment by miwarnec** [comment] 2019-12-26 20:19
can't reproduce in latest version.
feel free to reopen with more details. maybe it was fixed in one of the last changes.

**Closed as completed by miwarnec** 2019-12-26 20:19 UTC
